# PostgreSQL version
# gem install pg
development:
  adapter: postgresql
  encoding: utf8
  username:
  password:
  database: gallery_development

test:
  adapter: postgresql
  encoding: utf8
  username:
  password:
  database: gallery_test

production:
  adapter: postgresql
  encoding: utf8
  username:
  password:
  database: gallery_production