Parse:
#  cron: '* 15 * * * *'
#  cron: '* 30 * * * *'
  every: 2030s
#  every: 1hr
  class: Parser
  description: 'get new images every 6 hours '

TmpCleaner:
#  cron: '* 30 * * * *'
#  cron: '* * * 1 * *'
  every: 2030s
  class: TmpCleaner
  description: 'clear old images'